---
# handlers file for bamboo

- name: restart bamboo
  become: yes
  service:
    name: bamboo
    state: restarted
    pattern: bamboo
  tags:
    - bamboo

- name: enable bamboo service
  become: yes
  shell: systemctl enable bamboo
